"""empty message

Revision ID: 3724a89a75e3
Revises: 
Create Date: 2026-05-12 11:40:52.382621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3724a89a75e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_auth_user_email'), 'auth_user', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_auth_user_username'), 'auth_user', ['username'], unique=True, schema='public')
    op.create_table('blog_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_blog_category_id'), 'blog_category', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_blog_category_slug'), 'blog_category', ['slug'], unique=True, schema='public')
    op.create_table('blog_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_blog_location_id'), 'blog_location', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_blog_location_name'), 'blog_location', ['name'], unique=False, schema='public')
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['public.auth_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['public.blog_category.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['public.blog_location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('blog_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['public.auth_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['public.blog_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_blog_comment_author_id'), 'blog_comment', ['author_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_blog_comment_post_id'), 'blog_comment', ['post_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_blog_comment_post_id'), table_name='blog_comment', schema='public')
    op.drop_index(op.f('ix_public_blog_comment_author_id'), table_name='blog_comment', schema='public')
    op.drop_table('blog_comment', schema='public')
    op.drop_table('blog_post', schema='public')
    op.drop_index(op.f('ix_public_blog_location_name'), table_name='blog_location', schema='public')
    op.drop_index(op.f('ix_public_blog_location_id'), table_name='blog_location', schema='public')
    op.drop_table('blog_location', schema='public')
    op.drop_index(op.f('ix_public_blog_category_slug'), table_name='blog_category', schema='public')
    op.drop_index(op.f('ix_public_blog_category_id'), table_name='blog_category', schema='public')
    op.drop_table('blog_category', schema='public')
    op.drop_index(op.f('ix_public_auth_user_username'), table_name='auth_user', schema='public')
    op.drop_index(op.f('ix_public_auth_user_email'), table_name='auth_user', schema='public')
    op.drop_table('auth_user', schema='public')
    # ### end Alembic commands ###
