"""empty message

Revision ID: 64f408aace5d
Revises: fed96959ca5b
Create Date: 2026-05-12 08:32:33.581381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f408aace5d'
down_revision: Union[str, Sequence[str], None] = 'fed96959ca5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blog_comment_post_id_fkey'), 'blog_comment', type_='foreignkey')
    op.drop_constraint(op.f('blog_comment_author_id_fkey'), 'blog_comment', type_='foreignkey')
    op.create_foreign_key(None, 'blog_comment', 'blog_post', ['post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_comment', 'auth_user', ['author_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('blog_post_location_id_fkey'), 'blog_post', type_='foreignkey')
    op.drop_constraint(op.f('blog_post_author_id_fkey'), 'blog_post', type_='foreignkey')
    op.drop_constraint(op.f('blog_post_category_id_fkey'), 'blog_post', type_='foreignkey')
    op.create_foreign_key(None, 'blog_post', 'blog_category', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'blog_post', 'blog_location', ['location_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'blog_post', 'auth_user', ['author_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_post', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'blog_post', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'blog_post', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('blog_post_category_id_fkey'), 'blog_post', 'blog_category', ['category_id'], ['id'])
    op.create_foreign_key(op.f('blog_post_author_id_fkey'), 'blog_post', 'auth_user', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('blog_post_location_id_fkey'), 'blog_post', 'blog_location', ['location_id'], ['id'])
    op.drop_constraint(None, 'blog_comment', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'blog_comment', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('blog_comment_author_id_fkey'), 'blog_comment', 'auth_user', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('blog_comment_post_id_fkey'), 'blog_comment', 'blog_post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
