"""add post reactions

Revision ID: 8b5fe014ea77
Revises: 3724a89a75e3
Create Date: 2026-05-22 10:13:29.770133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5fe014ea77'
down_revision: Union[str, Sequence[str], None] = '3724a89a75e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['public.blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_user_reaction'),
    schema='public'
    )
    op.drop_constraint(op.f('blog_comment_post_id_fkey'), 'blog_comment', type_='foreignkey')
    op.drop_constraint(op.f('blog_comment_author_id_fkey'), 'blog_comment', type_='foreignkey')
    op.create_foreign_key(None, 'blog_comment', 'blog_post', ['post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_comment', 'auth_user', ['author_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('blog_post_location_id_fkey'), 'blog_post', type_='foreignkey')
    op.drop_constraint(op.f('blog_post_author_id_fkey'), 'blog_post', type_='foreignkey')
    op.drop_constraint(op.f('blog_post_category_id_fkey'), 'blog_post', type_='foreignkey')
    op.create_foreign_key(None, 'blog_post', 'blog_category', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'blog_post', 'auth_user', ['author_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_post', 'blog_location', ['location_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_post', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'blog_post', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'blog_post', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('blog_post_category_id_fkey'), 'blog_post', 'blog_category', ['category_id'], ['id'])
    op.create_foreign_key(op.f('blog_post_author_id_fkey'), 'blog_post', 'auth_user', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('blog_post_location_id_fkey'), 'blog_post', 'blog_location', ['location_id'], ['id'])
    op.drop_constraint(None, 'blog_comment', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'blog_comment', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('blog_comment_author_id_fkey'), 'blog_comment', 'auth_user', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('blog_comment_post_id_fkey'), 'blog_comment', 'blog_post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_table('blog_post_reaction', schema='public')
    # ### end Alembic commands ###
