"""empty message

Revision ID: ab0e33240b44
Revises: a4c85557fd04
Create Date: 2026-05-10 11:37:19.130880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab0e33240b44'
down_revision: Union[str, Sequence[str], None] = 'a4c85557fd04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('auth_user_email_key'), 'auth_user', type_='unique')
    op.drop_constraint(op.f('auth_user_username_key'), 'auth_user', type_='unique')
    op.create_index(op.f('ix_public_auth_user_email'), 'auth_user', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_auth_user_username'), 'auth_user', ['username'], unique=True, schema='public')
    op.alter_column('blog_category', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('blog_category_slug_key'), 'blog_category', type_='unique')
    op.create_index(op.f('ix_public_blog_category_id'), 'blog_category', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_blog_category_slug'), 'blog_category', ['slug'], unique=True, schema='public')
    op.alter_column('blog_comment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_public_blog_comment_author_id'), 'blog_comment', ['author_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_blog_comment_post_id'), 'blog_comment', ['post_id'], unique=False, schema='public')
    op.drop_constraint(op.f('blog_comment_post_id_fkey'), 'blog_comment', type_='foreignkey')
    op.drop_constraint(op.f('blog_comment_author_id_fkey'), 'blog_comment', type_='foreignkey')
    op.create_foreign_key(None, 'blog_comment', 'auth_user', ['author_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_comment', 'blog_post', ['post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('blog_location', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_public_blog_location_id'), 'blog_location', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_blog_location_name'), 'blog_location', ['name'], unique=False, schema='public')
    op.alter_column('blog_post', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('blog_post_category_id_fkey'), 'blog_post', type_='foreignkey')
    op.drop_constraint(op.f('blog_post_location_id_fkey'), 'blog_post', type_='foreignkey')
    op.drop_constraint(op.f('blog_post_author_id_fkey'), 'blog_post', type_='foreignkey')
    op.create_foreign_key(None, 'blog_post', 'auth_user', ['author_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_post', 'blog_category', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'blog_post', 'blog_location', ['location_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_post', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'blog_post', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'blog_post', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('blog_post_author_id_fkey'), 'blog_post', 'auth_user', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('blog_post_location_id_fkey'), 'blog_post', 'blog_location', ['location_id'], ['id'])
    op.create_foreign_key(op.f('blog_post_category_id_fkey'), 'blog_post', 'blog_category', ['category_id'], ['id'])
    op.alter_column('blog_post', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_public_blog_location_name'), table_name='blog_location', schema='public')
    op.drop_index(op.f('ix_public_blog_location_id'), table_name='blog_location', schema='public')
    op.alter_column('blog_location', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'blog_comment', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'blog_comment', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('blog_comment_author_id_fkey'), 'blog_comment', 'auth_user', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('blog_comment_post_id_fkey'), 'blog_comment', 'blog_post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_blog_comment_post_id'), table_name='blog_comment', schema='public')
    op.drop_index(op.f('ix_public_blog_comment_author_id'), table_name='blog_comment', schema='public')
    op.alter_column('blog_comment', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_public_blog_category_slug'), table_name='blog_category', schema='public')
    op.drop_index(op.f('ix_public_blog_category_id'), table_name='blog_category', schema='public')
    op.create_unique_constraint(op.f('blog_category_slug_key'), 'blog_category', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('blog_category', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_public_auth_user_username'), table_name='auth_user', schema='public')
    op.drop_index(op.f('ix_public_auth_user_email'), table_name='auth_user', schema='public')
    op.create_unique_constraint(op.f('auth_user_username_key'), 'auth_user', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('auth_user_email_key'), 'auth_user', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
